# CSC311 Machine Learning Project 2019 - Group 14

## This notebook performs the Support Vector Machine optimized technique.

# Libraries

The folowing code we will be talking about is the libraries that will be used to find aspects of `Phase 1B`

In [1]:
import pandas as pd 
import scipy as sp
import numpy as np
import pickle

# Reading Files

Read in the data files which we created in dividedata. We will read in the files of `group14_train` and `group14_cv`.

In [2]:
train_data = pd.read_csv("dividing data/train_data.csv")
cv_data = pd.read_csv("dividing data/cv_data.csv")

# Removing values
In the cell below we use the pop function to remove the columns such as `Unnamed` and `User` from the the `training data ` and our `cross validation ` data. We remove these columns because they are not important to the testing of our models.

In [3]:
train_data.pop('Unnamed: 0')
train_data.pop('User')
train_data.head(5)

,X0,Y0,Z0,X1,Y1,Z1,X2,Y2,Z2,X3,Y3,Z3,X4,Y4,Z4,Class
0,0.094568,-0.292415,-0.829242,0.808311,-0.999832,-1.061223,-0.428011,-0.005781,-0.479768,1.029530,-0.290812,-1.032775,0.222251,-1.573760,-0.951098,1
1,0.164180,-0.273078,-0.747491,-0.365735,-0.031963,-0.398817,0.866498,-0.920805,-0.963154,1.096778,-0.275489,-0.950012,0.294329,-1.548137,-0.883220,1
2,0.143341,-0.268184,-0.765351,-0.401403,-0.029721,-0.427667,0.843033,-0.913344,-0.982305,1.078122,-0.263563,-0.962075,0.297303,-1.547822,-0.884921,1
3,0.127342,-0.286601,-0.797402,-0.445771,-0.048139,-0.488997,1.082142,-0.326436,-1.026781,0.313101,-1.619450,-0.901480,0.769057,-0.828111,-0.970809,1
4,0.121584,-0.293168,-0.811300,-0.457774,-0.055671,-0.509653,0.798506,-0.940504,-1.036591,1.063978,-0.287236,-0.998353,0.284953,-1.569986,-0.895653,1

In [4]:
cv_data.pop('Unnamed: 0')
cv_data.pop('User')
cv_data.head(5)

,X0,Y0,Z0,X1,Y1,Z1,X2,Y2,Z2,X3,Y3,Z3,X4,Y4,Z4,Class
0,-0.011697,-1.180810,-2.183332,-1.556744,-1.125719,-1.848526,-0.829392,-0.905204,-1.866450,-1.782878,-0.835387,-1.161360,-1.843616,-1.779319,-1.238216,1
1,0.104689,-1.109310,-2.081804,-0.800283,-0.935223,-1.959605,-1.309219,-0.937808,-1.625959,-1.696088,-0.755318,-1.118794,0.065550,-1.865397,-1.712987,1
2,-1.752188,-1.097561,-1.479767,0.405706,-1.029926,-1.567298,-0.983402,-0.980608,-1.576618,-0.295130,-0.795591,-1.540360,-1.712344,-1.597558,-1.312438,1
3,-1.542486,-0.787810,-1.230008,0.642335,-0.907011,-1.142941,-0.750520,-0.731605,-1.335020,0.629459,-1.875332,-1.323578,-0.107134,-2.100910,0.625367,1
4,0.611151,-0.930368,-1.166071,-0.217071,-0.695173,-1.368207,-0.736484,-0.621722,-1.210286,0.367565,-1.796048,-0.929874,0.623902,-1.644653,-1.262047,1

# Declaring variables
Below we take the data from training_data and crossval_data and split it up into corresponding variables. With the training data, we take all the columns except the last column "Label" and store it into the variable "X_train" and only the last column into the variable "y_train". We do the exact same with the cross validation data, storing all the columns except the last into the variable "X_test" and the last column into the variable "y_test".

In [5]:
X_train = train_data.drop('Class', axis=1) 
y_train = train_data['Class']

X_test = cv_data.drop('Class', axis=1) 
y_test = cv_data['Class']

# Libraries

The folowing code we will be talking about is the libraries that will be used to find aspects of `Phase 1B`


`from sklearn import metrics`

`from sklearn.metrics import accuracy_score` - This library is to make use of the classifier accuracy_score() to obtain overall accuracy

`from sklearn.metrics import classification_report,confusion_matrix` - This library is imported to make use of the classification_report() and confusion_matrix() classifier

In [6]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report

# Model building 
Fitting, prediction and accuracy of the model.
In the cells below, I play around with the Support Vector Machine trying to find the best model

In [ ]:
Cost_Array = np.array([2**-3,2**-1,2,2**3,2**5,2**7,2**9,2**11])
Gamma_Array = np.array([2**-11,2**-9,2**-7,2**-5,2**-3,2**-1,2,2**3])
  

count = 0
for cost in range(len(Cost_Array)):
    
    for gamma in range(len(Gamma_Array)):
       
        model = SVC(kernel='rbf',  gamma=Gamma_Array[gamma], C=Cost_Array[cost] )
        model.fit(X_train, y_train)
        

        y_pred = model.predict(X_test)
        y_pred = list(map(float, y_pred))
        y_test = list(map(int, y_test))

            
        count+=1    
        print(str(count)+"\tcost = "+str(Cost_Array[cost])+"\tGamma = "+str(Gamma_Array[gamma]))
        print(metrics.accuracy_score(y_test, y_pred))

# Printing the Training score

This is to print out the training score we have obtained for our training set. This is to check at the correctness for our model hypothesis.

In [ ]:
svclassifier = SVC(kernel='rbf', C = 0.5, gamma = 0.03125)  
svclassifier.fit(X_train, y_train) 

y_pred = svclassifier.predict(X_test)
y_pred = list(map(float, y_pred))
y_test = list(map(int, y_test))

print(classification_report(y_test, y_pred))  
print("Cost = 0.5 and Gamma = 0.03125 provides the best average precision of 0.75")

In [ ]:
metrics.accuracy_score(y_test, y_pred)

# Model 
The following will be making use of the pickle library and function save the Support Vector Machine

In [ ]:
%store svclassifier